spring:
  datasource:
    url: jdbc:mysql://${AWS_DB_URL}:3306/babzip?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${AWS_DB_USERNAME}
    password: ${AWS_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: babzip-bucket
    stack:
      auto:false
    credentials:
      secret-key:
      access-key:

